version: "3"
services:
  bot:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - db
    environment:
    - MONGODB_SERVER=db
    - MONGODB_PORT=27017
    - MONGODB_DB=finnbot
  db:
    image: andresvidal/rpi3-mongodb3
    ports:
    - "27017:27017"